[project]
name = "Hellsing"
version = "0.1.0"
description = "Active Domain Webhook Manager" 

readme = "README.md"
requires-python = "^3.11 || ^3.12"
dependencies = [
    "discord-py (>=2.4.0,<3.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "discord-pretty-help (>=2.0.7,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
